### ISSUE TITLE
WC_Product can throw exception in WC 3.0.0

### ISSUE THREAD

**Issue by mikejolley** [afterpay/afterpay-woocommerce#9] opened 2017-04-07 20:25 UTC
See https://wordpress.org/support/topic/afterpay-plugin-conflict/#post-9007953 for background and the fix.

**Comment by webhotdesigns** [comment] 2017-04-11 07:01
I am getting same error with afterpay. What exactly should I do to update the plug in as I'm not experienced with coding and not confident to edit the core files.

**Comment by SnugSite** [comment] 2017-04-11 23:34
Replace this chunk of code: https://github.com/afterpay/afterpay-woocommerce/blob/667a58f5d2a949338286d4cecb50821efd12fbed/woocommerce-afterpay.php#L411-L427

...with this code: https://gist.github.com/mikejolley/586792dcadb26688f0a80d6b694bdb0e

...in this file: /wp-content/plugins/woocommerce-gateway-afterpay/woocmmerce-afterpay.php

(Make a backup copy before editing)

**Comment by stevenocta** [comment] 2017-04-12 07:44
Hi everyone, 

This issue has been fixed. 
As outlined above the issue is due to WC_Product class we used to support older versions of WooCommerce. It is fixed by replacing the "new WC_Product()" with "wc_get_product()" function.

**Closed** 2017-04-12 07:44 UTC

**Comment by mrmema** [comment] 2017-06-15 05:36
Hi, where I can get the latest version pls?  
https://github.com/afterpay/afterpay-woocommerce/tree/667a58f5d2a949338286d4cecb50821efd12fbed look like old version
Thanks

**Comment by YCowell** [comment] 2018-01-18 13:14
When Afterpay was enabled on my site, everything worked great.  Now the API will not trigger my site to tell me if the order is paid/processing.  All orders are on hold and then just cancel out.  How can I fix this?  I have to manually check if an order has been paid, I'm sick of going back and forth.  Also the poor customer does not get an order confirmation as the API has not triggered one?  Any ideas of how I can fix this?
